# Site settings
title: "Dan丁"
description: "这里是但丁，一个专注图文的网站"
baseurl: ""
url: "https://ethan-hu-hu.github.io"

# Google Analytics
#google_analytics: UA—XXXXXXXX-X


# Build settings
markdown:  kramdown
include:
  - _pages

# Assets
sass:
  sass_dir: _sass
  style: compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: 
  - Gemfile, 
  - Gemfile.lock
  - tale.gemspec
  - images

# Disqus (Set to your disqus id)
disqus:         jekyll-tale