# Site settings
title: "但丁的博客"
email: "ethanstyle007@outlook.com"
description: "你好，这是我的博客，专注图文分享"
baseurl: ""
url: "https://ethan-hu-hu.github.io" 
twitter_username: "EthanHu1314"
github_username: "ethan-hu-hu"

# Build settings
theme: minima
plugins:
  - jekyll-feed

